# Generated by Django 5.2 on 2026-03-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("status", models.CharField(choices=[("open", "open"), ("closed", "closed")], default="open", max_length=32)),
                ("priority", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={},
        ),
        migrations.CreateModel(
            name="Claim",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.CharField(max_length=128, unique=True)),
                ("claimant_name", models.CharField(blank=True, default="", max_length=255)),
                ("claimant_email", models.EmailField(blank=True, default="", max_length=254)),
                ("claimant_phone", models.CharField(blank=True, default="", max_length=64)),
                ("policy_number", models.CharField(blank=True, default="", max_length=128)),
                ("loss_date", models.DateField(blank=True, null=True)),
                ("loss_type", models.CharField(blank=True, default="", max_length=128)),
                ("loss_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("raw_payload", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        default="new",
                        help_text="Lifecycle: new, scored, queued, assigned, closed, archived",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={},
        ),
        migrations.CreateModel(
            name="Investigator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(max_length=150, unique=True)),
                ("display_name", models.CharField(blank=True, default="", max_length=255)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={},
        ),
        migrations.CreateModel(
            name="ScoringRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("enabled", models.BooleanField(default=True)),
                ("condition", models.JSONField()),
                ("score_delta", models.IntegerField(help_text="Score added when rule matches (can be negative).")),
                ("priority", models.IntegerField(default=100, help_text="Lower number runs earlier.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["priority", "id"],
            },
        ),
        migrations.CreateModel(
            name="Outcome",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "outcome_type",
                    models.CharField(
                        choices=[
                            ("fraud_confirmed", "fraud_confirmed"),
                            ("fraud_suspected", "fraud_suspected"),
                            ("legit", "legit"),
                            ("inconclusive", "inconclusive"),
                            ("withdrawn", "withdrawn"),
                        ],
                        max_length=64,
                    ),
                ),
                ("loss_avoided_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="outcome", to="api.claim"),
                ),
                (
                    "investigator",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.investigator"),
                ),
            ],
            options={},
        ),
        migrations.CreateModel(
            name="ClaimScore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total_score", models.IntegerField()),
                ("matched_rules", models.JSONField(default=list, help_text="List of matched rule names/ids and deltas.")),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="score_runs", to="api.claim"),
                ),
            ],
            options={},
        ),
        migrations.CreateModel(
            name="ClaimRelationship",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("same_claimant", "same_claimant"),
                            ("same_policy", "same_policy"),
                            ("same_phone", "same_phone"),
                            ("same_email", "same_email"),
                            ("same_address", "same_address"),
                            ("custom", "custom"),
                        ],
                        max_length=64,
                    ),
                ),
                ("key", models.CharField(help_text="Shared identifier that caused the link (e.g., phone/email).", max_length=255)),
                ("weight", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_claim",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="relationships_out", to="api.claim"),
                ),
                (
                    "target_claim",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="relationships_in", to="api.claim"),
                ),
            ],
            options={},
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ingested", "ingested"),
                            ("scored", "scored"),
                            ("queued", "queued"),
                            ("assigned", "assigned"),
                            ("outcome_recorded", "outcome_recorded"),
                            ("updated", "updated"),
                        ],
                        max_length=64,
                    ),
                ),
                ("actor", models.CharField(blank=True, default="", max_length=255)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="events", to="api.case"),
                ),
                (
                    "claim",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="events", to="api.claim"),
                ),
            ],
            options={},
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("assigned", "assigned"), ("in_progress", "in_progress"), ("completed", "completed")],
                        default="assigned",
                        max_length=32,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assignments", to="api.case"),
                ),
                (
                    "claim",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="api.claim"),
                ),
                (
                    "investigator",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="api.investigator"),
                ),
            ],
            options={},
        ),
        migrations.AddField(
            model_name="case",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_cases",
                to="api.investigator",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="claimrelationship",
            unique_together={("source_claim", "target_claim", "relationship_type", "key")},
        ),
        migrations.AlterUniqueTogether(
            name="assignment",
            unique_together={("claim", "investigator", "case")},
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(fields=["external_id"], name="api_claim_ex_external_6a2f4a_idx"),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(fields=["status", "-updated_at"], name="api_claim_st_status_23b0cd_idx"),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(fields=["policy_number"], name="api_claim_po_policy__7ed38d_idx"),
        ),
        migrations.AddIndex(
            model_name="scoringrule",
            index=models.Index(fields=["enabled", "priority"], name="api_scorin_enabled_1de6ef_idx"),
        ),
        migrations.AddIndex(
            model_name="claimscore",
            index=models.Index(fields=["claim", "-computed_at"], name="api_claimsc_claim_i_6a3f5e_idx"),
        ),
        migrations.AddIndex(
            model_name="claimscore",
            index=models.Index(fields=["-computed_at"], name="api_claimsc_computed_2e2b8c_idx"),
        ),
        migrations.AddIndex(
            model_name="investigator",
            index=models.Index(fields=["active"], name="api_invest_active_62f7aa_idx"),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["status", "-created_at"], name="api_case_st_status_8b4c55_idx"),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["priority", "status"], name="api_case_pr_priorit_6a5dc3_idx"),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(fields=["investigator", "status", "-updated_at"], name="api_assignm_investi_3c80e9_idx"),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(fields=["claim", "-assigned_at"], name="api_assignm_claim_i_efc71a_idx"),
        ),
        migrations.AddIndex(
            model_name="claimrelationship",
            index=models.Index(fields=["relationship_type", "key"], name="api_claimre_relati_15d8a0_idx"),
        ),
        migrations.AddIndex(
            model_name="claimrelationship",
            index=models.Index(fields=["source_claim"], name="api_claimre_source__7bfb23_idx"),
        ),
        migrations.AddIndex(
            model_name="claimrelationship",
            index=models.Index(fields=["target_claim"], name="api_claimre_target__8b0e77_idx"),
        ),
        migrations.AddIndex(
            model_name="outcome",
            index=models.Index(fields=["outcome_type", "-created_at"], name="api_outcom_outcom_1fd154_idx"),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["event_type", "-created_at"], name="api_audite_event_t_0a83ff_idx"),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["claim", "-created_at"], name="api_audite_claim_i_3a1f2a_idx"),
        ),
    ]
