# Generated by Django 5.2 on 2026-03-25 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assignment',
            new_name='api_assignm_investi_4d4e6e_idx',
            old_name='api_assignm_investi_3c80e9_idx',
        ),
        migrations.RenameIndex(
            model_name='assignment',
            new_name='api_assignm_claim_i_e05fa4_idx',
            old_name='api_assignm_claim_i_efc71a_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='api_auditev_event_t_1b8c10_idx',
            old_name='api_audite_event_t_0a83ff_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='api_auditev_claim_i_2b3c72_idx',
            old_name='api_audite_claim_i_3a1f2a_idx',
        ),
        migrations.RenameIndex(
            model_name='case',
            new_name='api_case_status_fedff2_idx',
            old_name='api_case_st_status_8b4c55_idx',
        ),
        migrations.RenameIndex(
            model_name='case',
            new_name='api_case_priorit_c2e49b_idx',
            old_name='api_case_pr_priorit_6a5dc3_idx',
        ),
        migrations.RenameIndex(
            model_name='claim',
            new_name='api_claim_externa_39bdd4_idx',
            old_name='api_claim_ex_external_6a2f4a_idx',
        ),
        migrations.RenameIndex(
            model_name='claim',
            new_name='api_claim_status_5f8a0d_idx',
            old_name='api_claim_st_status_23b0cd_idx',
        ),
        migrations.RenameIndex(
            model_name='claim',
            new_name='api_claim_policy__d0b521_idx',
            old_name='api_claim_po_policy__7ed38d_idx',
        ),
        migrations.RenameIndex(
            model_name='claimrelationship',
            new_name='api_claimre_relatio_33ee74_idx',
            old_name='api_claimre_relati_15d8a0_idx',
        ),
        migrations.RenameIndex(
            model_name='claimrelationship',
            new_name='api_claimre_source__3fc189_idx',
            old_name='api_claimre_source__7bfb23_idx',
        ),
        migrations.RenameIndex(
            model_name='claimrelationship',
            new_name='api_claimre_target__388ec6_idx',
            old_name='api_claimre_target__8b0e77_idx',
        ),
        migrations.RenameIndex(
            model_name='claimscore',
            new_name='api_claimsc_claim_i_eb8561_idx',
            old_name='api_claimsc_claim_i_6a3f5e_idx',
        ),
        migrations.RenameIndex(
            model_name='claimscore',
            new_name='api_claimsc_compute_ae5b36_idx',
            old_name='api_claimsc_computed_2e2b8c_idx',
        ),
        migrations.RenameIndex(
            model_name='investigator',
            new_name='api_investi_active_ccc687_idx',
            old_name='api_invest_active_62f7aa_idx',
        ),
        migrations.RenameIndex(
            model_name='outcome',
            new_name='api_outcome_outcome_158101_idx',
            old_name='api_outcom_outcom_1fd154_idx',
        ),
        migrations.RenameIndex(
            model_name='scoringrule',
            new_name='api_scoring_enabled_48e316_idx',
            old_name='api_scorin_enabled_1de6ef_idx',
        ),
    ]
